-- PostgreSQL schema (idempotente)

CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_name VARCHAR(120),
  brand_primary VARCHAR(16),
  brand_secondary VARCHAR(16),
  brand_accent VARCHAR(16),
  heat_low VARCHAR(16),
  heat_mid VARCHAR(16),
  heat_high VARCHAR(16),
  login_candidate_photo VARCHAR(255),
  login_bg_url VARCHAR(255),
  login_bg_type VARCHAR(10),
  login_bg_blur INT DEFAULT 0,
  login_bg_brightness INT DEFAULT 100,
  about_text TEXT
);

CREATE TABLE IF NOT EXISTS ra (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80) UNIQUE
);

CREATE TABLE IF NOT EXISTS roles (
  key_name VARCHAR(50) PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  immutable SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  phone VARCHAR(20),
  email VARCHAR(120),
  city VARCHAR(80),
  uf VARCHAR(2),
  message TEXT NOT NULL,
  created_at BIGINT
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(80),
  last_name VARCHAR(80),
  phone VARCHAR(20) UNIQUE,
  cpf VARCHAR(14),
  password_hash VARCHAR(120),
  address VARCHAR(255),
  cep VARCHAR(9),
  city VARCHAR(80),
  ra_id BIGINT REFERENCES ra(id) ON DELETE SET NULL,
  inviter_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  avatar_url VARCHAR(255),
  role_key VARCHAR(50) DEFAULT 'usuario',
  status VARCHAR(20) DEFAULT 'pending',
  goal_enabled SMALLINT DEFAULT 0,
  goal_total INT DEFAULT 0,
  created_at BIGINT
);
CREATE INDEX IF NOT EXISTS idx_users_inviter ON users(inviter_id);
CREATE INDEX IF NOT EXISTS idx_users_ra ON users(ra_id);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role_key);

CREATE TABLE IF NOT EXISTS presence (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  last_seen BIGINT
);

CREATE TABLE IF NOT EXISTS push_subs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  sub_json TEXT NOT NULL,
  created_at BIGINT
);

CREATE TABLE IF NOT EXISTS banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(120),
  image_url VARCHAR(255) NOT NULL,
  link_url VARCHAR(255),
  active SMALLINT DEFAULT 1,
  created_at BIGINT
);

CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(20) NOT NULL,
  content TEXT,
  media_url VARCHAR(255),
  options_json TEXT,
  event_date TEXT,
  event_place TEXT,
  likes INT DEFAULT 0,
  created_at BIGINT
);
CREATE INDEX IF NOT EXISTS idx_posts_author ON posts(author_id);

CREATE TABLE IF NOT EXISTS post_likes (
  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, user_id)
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  created_at BIGINT
);
CREATE INDEX IF NOT EXISTS idx_comments_post ON comments(post_id);

CREATE TABLE IF NOT EXISTS poll_votes (
  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  option_id VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, user_id)
);

CREATE TABLE IF NOT EXISTS invitations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(64) UNIQUE NOT NULL,
  inviter_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  full_name VARCHAR(160),
  phone VARCHAR(20),
  status VARCHAR(20) DEFAULT 'pending',
  pending_user_id BIGINT,
  created_at BIGINT
);
CREATE INDEX IF NOT EXISTS idx_invitations_inviter ON invitations(inviter_id);

CREATE TABLE IF NOT EXISTS permissions (
  role_key VARCHAR(50) NOT NULL,
  resource VARCHAR(80) NOT NULL,
  can_view SMALLINT DEFAULT 0,
  can_edit SMALLINT DEFAULT 0,
  can_delete SMALLINT DEFAULT 0,
  PRIMARY KEY (role_key, resource),
  FOREIGN KEY (role_key) REFERENCES roles(key_name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR(80) NOT NULL,
  actor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  target_id BIGINT,
  meta_json TEXT,
  created_at BIGINT
);

INSERT INTO roles(key_name, name, immutable) VALUES ('admin_master','Administrador Master',1)
ON CONFLICT (key_name) DO NOTHING;
INSERT INTO roles(key_name, name, immutable) VALUES ('administrador','Administrador',1)
ON CONFLICT (key_name) DO NOTHING;
INSERT INTO roles(key_name, name, immutable) VALUES ('moderador','Moderador',0)
ON CONFLICT (key_name) DO NOTHING;
INSERT INTO roles(key_name, name, immutable) VALUES ('usuario','Usuário',0)
ON CONFLICT (key_name) DO NOTHING;

INSERT INTO settings(id, site_name) VALUES (1, 'Gabinete+')
ON CONFLICT (id) DO NOTHING;
